### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by shy1st**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@shy1st plz fix CI.

**Comment by shy1st** [comment]
@hsluoyz plz review.

**Comment by hsluoyz** [comment]
@shy1st plz fix badges:

image

**Comment by shy1st** [comment]
@hsluoyz The "build" badge is associated with Travis CI, so I think we can delete it.
I don't have access to this project, so I can not add the codecov badge.And we will not develop this warehouse for the time being. so I think we also can delete it for the time being. So is the nutz-authz project.

**Pull request merged**
